/*
 * LeetCode 389: Find the Difference
 * 
 * Problem:
 * String t is generated by shuffling string s and adding one more letter
 * at a random position. Return the letter that was added to t.
 * 
 * Approach: ASCII Sum Difference
 * 
 * Key Insight:
 * - Sum ASCII values of all characters in both strings
 * - The difference equals the ASCII value of the added character
 * - sumT - sumS = ASCII of extra character
 * 
 * Algorithm:
 * 1. Calculate sum of ASCII values in s
 * 2. Calculate sum of ASCII values in t
 * 3. Difference = added character
 * 
 * Time Complexity: O(n) - iterate through both strings
 * Space Complexity: O(1) - only using two integer variables
 * 
 * Example: s = "abcd", t = "abcde"
 * 
 *   s = "abcd"
 *   sumS = 'a' + 'b' + 'c' + 'd'
 *        = 97 + 98 + 99 + 100
 *        = 394
 * 
 *   t = "abcde"
 *   sumT = 'a' + 'b' + 'c' + 'd' + 'e'
 *        = 97 + 98 + 99 + 100 + 101
 *        = 495
 * 
 *   Difference = 495 - 394 = 101 = 'e'
 * 
 * Example 2: s = "", t = "y"
 * 
 *   sumS = 0
 *   sumT = 'y' = 121
 *   Difference = 121 - 0 = 121 = 'y'
 * 
 * Visual:
 * 
 *   s: [a] [b] [c] [d]
 *       ↓   ↓   ↓   ↓
 *      97  98  99 100  → Sum = 394
 * 
 *   t: [a] [b] [c] [d] [e]
 *       ↓   ↓   ↓   ↓   ↓
 *      97  98  99 100 101 → Sum = 495
 * 
 *   495 - 394 = 101 = 'e' ✓
 * 
 * ============================================================
 * ALTERNATIVE APPROACHES
 * ============================================================
 * 
 * Approach 2: XOR (Bit Manipulation)
 * 
 *   public char findTheDifference(String s, String t) {
 *       char result = 0;
 *       for (char c : s.toCharArray()) result ^= c;
 *       for (char c : t.toCharArray()) result ^= c;
 *       return result;
 *   }
 * 
 *   XOR Insight:
 *   - a ^ a = 0 (same characters cancel out)
 *   - a ^ 0 = a (XOR with 0 keeps value)
 *   - All matching chars cancel, leaving the extra char
 * 
 *   Example: s = "ab", t = "abc"
 *   result = 'a' ^ 'b' ^ 'a' ^ 'b' ^ 'c'
 *          = ('a' ^ 'a') ^ ('b' ^ 'b') ^ 'c'
 *          = 0 ^ 0 ^ 'c'
 *          = 'c'
 * 
 * Approach 3: Frequency Count (Array)
 * 
 *   public char findTheDifference(String s, String t) {
 *       int[] count = new int[26];
 *       for (char c : s.toCharArray()) count[c - 'a']++;
 *       for (char c : t.toCharArray()) count[c - 'a']--;
 *       for (int i = 0; i < 26; i++) {
 *           if (count[i] == -1) return (char)(i + 'a');
 *       }
 *       return ' ';
 *   }
 * 
 *   Insight: Increment for s, decrement for t
 *   The character with count -1 is the extra one.
 * 
 * ============================================================
 * COMPARISON OF APPROACHES
 * ============================================================
 * 
 * | Approach     | Time | Space | Notes                    |
 * |--------------|------|-------|--------------------------|
 * | ASCII Sum    | O(n) | O(1)  | Simple, potential overflow|
 * | XOR          | O(n) | O(1)  | Elegant, no overflow     |
 * | Freq Count   | O(n) | O(26) | More intuitive           |
 */

class Solution {

    public char findTheDifference(String s, String t) {

        int sumS = 0;

        int sumT = 0;

        // sum of ASCII values of characters in s
        for (char c : s.toCharArray()) {

            sumS += c;

        }

        // sum of ASCII values of characters in t
        for (char c : t.toCharArray()) {

            sumT += c;

        }

        // the difference is the added character
        return (char)(sumT - sumS);

    }

}

